<?php

namespace Acme\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * example, not used
     * @param $user
     * @return mixed
     */
    public function getRelatedSeriesList($user) {

        $seasons = $this->getEntityManager()
            ->getRepository('AcmeUserBundle:User')
            ->createQueryBuilder('user')
            ->select('user', 'user_series', 'series')
            ->leftJoin('user.series', 'user_series')
            ->leftJoin('user_series.seriesId', 'series')
            ->where('user.id = :user')
            ->setParameter('user', $user)
            ->orderBy('series.name', 'ASC')
            ->getQuery()
            ->getSingleResult()
        ;
        return $seasons;
    }
}
