imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
        - AcmeRememberSeriesBundle
    #java: /usr/bin/java
    assets:
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/stylesheets/bootstrap.scss
    #            - %kernel.root_dir%/../vendor/twbs/bootstrap/less/responsive.less
            filters:
                - sass
                - compass
            output: css/bootstrap.css

        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/*
#                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/affix.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/alert.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/button.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/carousel.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/collapse.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/dropdown.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/tab.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/transition.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/scrollspy.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/modal.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/tooltip.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/javascripts/bootstrap/popover.js
            output: js/bootstrap.js

        jquery:
            inputs:
               - %kernel.root_dir%/../vendor/jquery/jquery/*
            output: js/jquery.js

        bootstrap_woff_fonts:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
            output: fonts/bootstrap/glyphicons-halflings-regular.woff
        bootstrap_ttf_fonts:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf
            output: fonts/bootstrap/glyphicons-halflings-regular.ttf
        bootstrap_eot_fonts:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot
            output: fonts/bootstrap/glyphicons-halflings-regular.eot
        bootstrap_svg_fonts:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.svg
            output: fonts/bootstrap/glyphicons-halflings-regular.svg

    filters:
        cssrewrite: ~
        sass:       ~
        compass:    ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Acme\UserBundle\Entity\User
