_welcome:
    pattern: /
    defaults: { _controller: AcmeRememberSeriesBundle:Default:index }

acme_remember_series_homepage:
    pattern:  /hello
    defaults: { _controller: AcmeRememberSeriesBundle:Default:index }

acme_remember_series_single_page:
    pattern:  /series/{series_id}
    defaults: { _controller: AcmeRememberSeriesBundle:Default:series }
