<?php

namespace Acme\RememberSeriesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends EntityRepository
{
    /**
     * join user to season
     */
    public function getSeasonsForUser($series_id, $user) {

        $seasons = $this->getEntityManager()
            ->getRepository('AcmeRememberSeriesBundle:Season')
            ->createQueryBuilder('season')
            ->select('season', 'user_series')
            ->leftJoin('season.users', 'user_series')
            ->where('season.seriesId = :series_id')
            ->andWhere('user_series.userId = :user OR user_series.userId IS NULL')
            ->setParameter('series_id', $series_id)
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult()
        ;
        return $seasons;
    }
}
