<?php

namespace Acme\RememberSeriesBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends EntityRepository
{
    /**
     * join user to season
     */
    public function getSeasonsForUser($series, $user) {
        
        $rsm = new ResultSetMapping();
        
        $rsm->addEntityResult('Acme\RememberSeriesBundle\Entity\Season', 's')
            ->addFieldResult('s', 'id', 'id')
            ->addFieldResult('s', 'name', 'name')
            ->addFieldResult('s', 'number', 'number')
            ->addFieldResult('s', 'description', 'description')
            ->addMetaResult('s', 'series_id', 'series_id')
            ->addJoinedEntityResult('Acme\RememberSeriesBundle\Entity\UserSeason' , 'u_s', 's', 'users')
            ->addMetaResult('u_s', 'user_id', 'user_id')
            ->addFieldResult('u_s', 'user_season_id', 'id');
        
        $sql = 'SELECT s.id, s.name, s.number, s.description, s.series_id, u_s.id AS user_season_id, u_s.user_id     
                FROM Season s 
                LEFT JOIN (
                    SELECT us.id, us.user_id, us.season_id 
                    FROM user_season us 
                    WHERE us.user_id = :user_id
                ) AS u_s ON u_s.season_id = s.id
                WHERE s.series_id = :series_id';
        
        $seasons = $this->getEntityManager()->createNativeQuery($sql, $rsm)
                        ->setParameter('series_id', $series)
                        ->setParameter('user_id', $user)
                        ->getResult();
        return $seasons;
    }
}
