<?php

namespace Acme\RememberSeriesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserSeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSeriesRepository extends EntityRepository
{
}
